const shiftConvert = ({moji}) => {
  switch(moji) {
    // か行
    case 'か':
      return 'が'
    case 'き':
      return 'ぎ'
    case 'く':
      return 'ぐ'
    case 'け':
      return 'げ'
    case 'こ':
      return 'ご'
    case 'が':
      return 'か'
    case 'ぎ':
      return 'き'
    case 'ぐ':
      return 'く'
    case 'げ':
      return 'け'
    case 'ご':
      return 'こ'
    // さ行
    case 'さ':
      return 'ざ'
    case 'し':
      return 'じ'
    case 'す':
      return 'ず'
    case 'せ':
      return 'ぜ'
    case 'そ':
      return 'ぞ'
    case 'ざ':
      return 'さ'
    case 'じ':
      return 'し'
    case 'ず':
      return 'す'
    case 'ぜ':
      return 'せ'
    case 'ぞ':
      return 'そ'
    // た行
    case 'た':
      return 'だ'
    case 'ち':
      return 'ぢ'
    case 'つ':
      return 'づ'
    case 'て':
      return 'で'
    case 'と':
      return 'ど'
    case 'だ':
      return 'た'
    case 'ぢ':
      return 'ち'
    case 'づ':
      return 'つ'
    case 'で':
      return 'て'
    case 'ど':
      return 'と'
    // や行
    case 'や':
      return 'ゃ'
    case 'ゆ':
      return 'ゅ'
    case 'よ':
      return 'ょ'
    case 'ゃ':
      return 'や'
    case 'ゅ':
      return 'ゆ'
    case 'ょ':
      return 'よ'
    // は行
    case 'は':
      return 'ば'
    case 'ひ':
      return 'び'
    case 'ふ':
      return 'ぶ'
    case 'へ':
      return 'べ'
    case 'ほ':
      return 'ぼ'
    case 'ば':
      return 'ぱ'
    case 'び':
      return 'ぴ'
    case 'ぶ':
      return 'ぷ'
    case 'べ':
      return 'ぺ'
    case 'ぼ':
      return 'ぽ'
    case 'ぱ':
      return 'は'
    case 'ぴ':
      return 'ひ'
    case 'ぷ':
      return 'ふ'
    case 'ぺ':
      return 'へ'
    case 'ぽ':
      return 'ほ'
    // カタカナ
    // カ行
    case 'カ':
      return 'ガ'
    case 'キ':
      return 'ギ'
    case 'ク':
      return 'グ'
    case 'ケ':
      return 'ゲ'
    case 'コ':
      return 'ゴ'
    case 'ガ':
      return 'カ'
    case 'ギ':
      return 'キ'
    case 'グ':
      return 'ク'
    case 'ゲ':
      return 'け'
    case 'ゴ':
      return 'こ'
    // サ行
    case 'サ':
      return 'ザ'
    case 'シ':
      return 'ジ'
    case 'ス':
      return 'ズ'
    case 'セ':
      return 'ゼ'
    case 'ソ':
      return 'ゾ'
    case 'ザ':
      return 'サ'
    case 'ジ':
      return 'シ'
    case 'ズ':
      return 'ス'
    case 'ゼ':
      return 'セ'
    case 'ゾ':
      return 'ソ'
    // タ行
    case 'タ':
      return 'ダ'
    case 'チ':
      return 'ヂ'
    case 'ツ':
      return 'ヅ'
    case 'テ':
      return 'デ'
    case 'ト':
      return 'ド'
    case 'ダ':
      return 'タ'
    case 'ヂ':
      return 'チ'
    case 'ヅ':
      return 'ツ'
    case 'デ':
      return 'テ'
    case 'ド':
      return 'ト'
    // ヤ行
    case 'ヤ':
      return 'ャ'
    case 'ユ':
      return 'ュ'
    case 'ヨ':
      return 'ョ'
    case 'ャ':
      return 'ヤ'
    case 'ュ':
      return 'ユ'
    case 'ョ':
      return 'ヨ'
    // ハ行
    case 'ハ':
      return 'バ'
    case 'ヒ':
      return 'ビ'
    case 'フ':
      return 'ブ'
    case 'ヘ':
      return 'ベ'
    case 'ホ':
      return 'ボ'
    case 'バ':
      return 'パ'
    case 'ビ':
      return 'ピ'
    case 'ブ':
      return 'プ'
    case 'ベ':
      return 'ペ'
    case 'ボ':
      return 'ポ'
    case 'パ':
      return 'ハ'
    case 'ピ':
      return 'ヒ'
    case 'プ':
      return 'フ'
    case 'ペ':
      return 'ヘ'
    case 'ポ':
      return 'ホ'
    default:
      return moji
  }
}

const shiftKanaKeyLabel = ({kanaMode}) => {
  if(kanaMode === 'katakana') return 'あいう'
  return 'アイウ'
}

export { shiftConvert, shiftKanaKeyLabel }